package com.healthwise.auth.service;
import com.healthwise.auth.dto.AuthDtos.*; import com.healthwise.auth.entity.RefreshToken; import com.healthwise.auth.repository.RefreshTokenRepository; import com.healthwise.config.JwtProperties; import com.healthwise.exception.ConflictException; import com.healthwise.exception.ResourceNotFoundException; import com.healthwise.security.JwtService; import com.healthwise.user.entity.User; import com.healthwise.user.repository.UserRepository; import java.security.SecureRandom; import java.time.Instant; import java.util.Base64; import org.slf4j.Logger; import org.slf4j.LoggerFactory; import org.springframework.security.crypto.password.PasswordEncoder; import org.springframework.stereotype.Service;
/** Registration, login, refresh rotation, and logout operations. */
@Service public class AuthService { private static final Logger log=LoggerFactory.getLogger(AuthService.class); private final UserRepository users; private final RefreshTokenRepository refresh; private final PasswordEncoder encoder; private final JwtService jwt; private final JwtProperties props; public AuthService(UserRepository u,RefreshTokenRepository r,PasswordEncoder e,JwtService j,JwtProperties p){users=u;refresh=r;encoder=e;jwt=j;props=p;}
 public Tokens register(Register req){String email=req.email().trim().toLowerCase();if(users.existsByEmailIgnoreCase(email))throw new ConflictException("Email is already registered");User u=new User();u.setEmail(email);u.setPassword(encoder.encode(req.password()));u.setFirstName(req.firstName().trim());u.setLastName(req.lastName().trim());users.save(u);log.info("Registered user {}",u.getId());return tokens(u);}
 public Tokens login(Login req){User u=users.findByEmailIgnoreCase(req.email().trim()).orElseThrow(()->new IllegalArgumentException("Invalid email or password"));if(!u.isEnabled()||!encoder.matches(req.password(),u.getPassword()))throw new IllegalArgumentException("Invalid email or password");log.info("Authenticated user {}",u.getId());return tokens(u);}
 public Tokens refresh(String raw){RefreshToken token=refresh.findByToken(raw).orElseThrow(()->new IllegalArgumentException("Invalid refresh token"));if(token.getExpiresAt().isBefore(Instant.now())){refresh.delete(token);throw new IllegalArgumentException("Refresh token expired");}User user=users.findById(token.getUserId()).orElseThrow(()->new ResourceNotFoundException("User not found"));refresh.delete(token);return tokens(user);}
 public void logout(String raw){if(raw!=null)refresh.findByToken(raw).ifPresent(refresh::delete);}
 private Tokens tokens(User u){refresh.deleteByUserId(u.getId());RefreshToken r=new RefreshToken();byte[] bytes=new byte[48];new SecureRandom().nextBytes(bytes);r.setToken(Base64.getUrlEncoder().withoutPadding().encodeToString(bytes));r.setUserId(u.getId());r.setExpiresAt(Instant.now().plusSeconds(props.refreshTokenDays()*86400));refresh.save(r);return new Tokens(jwt.createAccessToken(u),r.getToken(),"Bearer");}}
