server:
  port: 8080

spring:
  application:
    name: assessment-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/healthwise
      auto-index-creation: true
  jackson:
    deserialization:
      fail-on-unknown-properties: false

healthwise:
  assessment:
    default-version: v1

cors:
  allowed-origins: http://localhost:5173,http://localhost:5174,http://localhost:5175
